### ISSUE TITLE
Zeppelin 0.7-SNAPSHOT + Spark 2.0

### ISSUE THREAD

**Issue by n1o** [knockdata/zeppelin-highcharts#9]
Hey,

your project seems promising, i really miss some visualization library for Scala + Spark in Zeppelin. But since i added your package as a dependency I am running into this exception:

```
%spark
sc.version
```

```
INFO [2016-08-10 08:14:19,526] ({pool-2-thread-2} NotebookServer.java[afterStatusChange]:1285) - Job 20160810-080805_1007943900 is finished
...skipping...
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
        at org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess.getClient(RemoteInterpreterProcess.java:96)
        at org.apache.zeppelin.scheduler.RemoteScheduler$JobStatusPoller.getStatus(RemoteScheduler.java:254)
        at org.apache.zeppelin.scheduler.RemoteScheduler$JobRunner.run(RemoteScheduler.java:342)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
        at org.apache.zeppelin.interpreter.remote.ClientFactory.create(ClientFactory.java:51)
        ... 15 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
        ... 16 more
ERROR [2016-08-10 15:29:53,424] ({pool-2-thread-36} NotebookServer.java[afterStatusChange]:1280) - Error
org.apache.zeppelin.interpreter.InterpreterException: org.apache.zeppelin.interpreter.InterpreterException: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.init(RemoteInterpreter.java:218)
        at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.getFormType(RemoteInterpreter.java:383)
        at org.apache.zeppelin.interpreter.LazyOpenInterpreter.getFormType(LazyOpenInterpreter.java:105)
        at org.apache.zeppelin.notebook.Paragraph.jobRun(Paragraph.java:290)
        at org.apache.zeppelin.scheduler.Job.run(Job.java:176)
        at org.apache.zeppelin.scheduler.RemoteScheduler$JobRunner.run(RemoteScheduler.java:329)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.zeppelin.interpreter.InterpreterException: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.zeppelin.interpreter.remote.ClientFactory.create(ClientFactory.java:53)
        at org.apache.zeppelin.interpreter.remote.ClientFactory.create(ClientFactory.java:37)
        at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:861)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
        at org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess.getClient(RemoteInterpreterProcess.java:96)
        at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.init(RemoteInterpreter.java:216)
        ... 12 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
        at org.apache.zeppelin.interpreter.remote.ClientFactory.create(ClientFactory.java:51)
        ... 19 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
        ... 20 more
 INFO [2016-08-10 15:29:53,424] ({pool-2-thread-36} NotebookServer.java[afterStatusChange]:1285) - Job 20160810-152912_912073533 is finished
```

I cant really tell anything meaningful from the exception. 

I am running it on spark 2.0 and Zeppelin built from the actual master branch. I am not sure if this error is related to your package or with my setup. So if you fail to reproduce the error feel free to close this issue.

**Comment by knockdata** [comment]
Thanks very much for trying zeppelin-highcharts. 

zeppelin-highcharts by default is compiled with Spark 1.6. It has not been verified on Spark 2.0 yet. 

I will add maven profile to support both Spark 1.6 and 2.0 in the coming days.

**Comment by rockiey** [comment]
I just tested on commit 85d4df4f0c9801751abad57004760ccc10d1eb82.

When I run with default build which is spark-2.0 & scala-2.10. sc.version can NOT be executed correctly.

    mvn clean package -DskipTests

When I compile scala-2.11. sc.version can be executed correctly.

    mvn clean package -Pspark-2.0 -Pscala-2.11 -DskipTests

@n1o Please test without zeppelin-highcharts to see if it works in your setup.

**Comment by rockiey** [comment]
@n1o I added spark 2.0 support. Please verify if it's working. Ref to the latest README.md file, I have updated to add spark 2.0 support. 

zeppelin is compiled with 

    mvn clean package -Pspark-2.0 -Pscala-2.11 -DskipTests

zeppelin-highcharts is compiled with 

    mvn clean package -Pspark-2.0 -DskipTests

**Comment by n1o** [comment]
Hey, your amazing 👍 everything works fine. I am going to close this issue

**Comment by qgxiaozhan** [comment]
@n1o  How do you fix it ? Have you  truned on [https://zeppelin.apache.org/docs/0.7.0/manual/userimpersonation.html](https://zeppelin.apache.org/docs/0.7.0/manual/userimpersonation.html)
